Repository google/fuzzbench, pull requests merged in 2020-06, with the labels that each got.

#352 Add support for retrying preemptible trials.
  analysis/data_utils.py
  analysis/queries.py
  common/experiment_utils.py
  common/gce.py
  common/gcloud.py
  common/test_gce.py
  common/test_gcloud.py
  database/alembic/versions/72f7db0e7dfe_support_preemptibles.py
  database/models.py
  experiment/dispatcher.py
  experiment/measurer.py
  experiment/reporter.py
  experiment/runner.py
  experiment/scheduler.py
  experiment/test_dispatcher.py
  experiment/test_measurer.py
  experiment/test_scheduler.py
  requirements.txt
Labels: cla: yes

#393 Support running measure_worker on different machines than the manager
  common/experiment_utils.py
  common/gsutil.py
  experiment/measurer/measure_manager.py
  experiment/measurer/measure_worker.py
  experiment/measurer/test_data/covered-pcs.txt
  experiment/measurer/test_measure_worker.py
Labels: cla: yes

#395 Don't delete entire venv when requirements.txt is updated.
  Makefile
Labels: cla: yes

#388 Remove make templates for fuzzers/benchmarks and support variants.
  .gitignore
  Makefile
  docker/build.mk
  docker/generate_makefile.py
Labels: cla: yes

#394 [refactor] gsutil => filestore_utils; local support prep
  common/filestore_utils.py
  experiment/build/build_utils.py
  experiment/build/local_build.py
  experiment/measurer.py
  experiment/reporter.py
  experiment/run_experiment.py
  experiment/runner.py
  experiment/test_measurer.py
  experiment/test_run_experiment.py
  experiment/test_runner.py
Labels: cla: yes

#407 Fix argument in handling in filestore_utils
  common/filestore_utils.py
  common/gsutil.py
  common/test_filestore_utils.py
  experiment/measurer.py
  experiment/test_measurer.py
Labels: cla: yes

#409 [NFC] Replace uses of side_effect with return_value.
  experiment/test_run_experiment.py
Labels: cla: yes

#410 [NFC] Remove unused logger.
  common/filestore_utils.py
Labels: cla: yes

#404 make stdin work for afl++ shmem
  fuzzers/aflplusplus/builder.Dockerfile
  fuzzers/aflplusplus_optimal/builder.Dockerfile
  fuzzers/aflplusplus_optimal_shmem/builder.Dockerfile
  fuzzers/aflplusplus_qemu/builder.Dockerfile
  fuzzers/aflplusplus_shmem/builder.Dockerfile
Labels: cla: no

#413 Remove --upgrade flag from pip install
  Makefile
Labels: cla: yes

#414 Some last cleanup to the queue/scalable measurer branch.
  .dockerignore
  docker/dispatcher-image/startup-dispatcher.sh
  service/experiment-config.yaml
Labels: cla: yes

#415 Use filestore_utils in queue code
  common/filestore_utils.py
  common/gsutil.py
  experiment/measurer/measure_worker.py
  experiment/measurer/test_measure_manager.py
  experiment/measurer/test_measure_worker.py
Labels: cla: yes

#406 local dispatcher: from gsutil to rsync
  docker/base-image/Dockerfile
  experiment/run_experiment.py
Labels: cla: yes

#426 Ensure FORCE_LOCAL=1 for presubmit.
  common/utils.py
  presubmit.py
Labels: cla: yes

#423 Aflcc integration
  .github/workflows/fuzzers.yml
  fuzzers/aflcc/aflcc_mock.c
  fuzzers/aflcc/builder.Dockerfile
  fuzzers/aflcc/fuzzer.py
  fuzzers/aflcc/runner.Dockerfile
Labels: cla: yes

#432 [libfuzzer] Add libfuzzer variant that doesn't use cmp instrumentation
  .github/workflows/fuzzers.yml
  fuzzers/libfuzzer_nocmp/builder.Dockerfile
  fuzzers/libfuzzer_nocmp/fuzzer.py
  fuzzers/libfuzzer_nocmp/runner.Dockerfile
Labels: cla: yes

#405 [NFC] add (but not enable) `local_filestore` module and its unit tests
  common/filestore_utils.py
  common/gsutil.py
  common/local_filestore.py
  common/test_local_filestore.py
Labels: cla: yes, dependencies, new feature

#431 shmem tests
  fuzzers/aflplusplus/builder.Dockerfile
  fuzzers/aflplusplus_optimal/builder.Dockerfile
  fuzzers/aflplusplus_optimal_shmem/builder.Dockerfile
  fuzzers/aflplusplus_qemu/builder.Dockerfile
  fuzzers/aflplusplus_shmem/builder.Dockerfile
Labels: cla: no

#416 Make automatic_run_experiment run experiments based on requests
  presubmit.py
  service/automatic_run_experiment.py
  service/experiment-requests.yaml
  service/test_automatic_run_experiment.py
Labels: cla: yes

#435 fix shmem
  fuzzers/aflplusplus/builder.Dockerfile
  fuzzers/aflplusplus_optimal/builder.Dockerfile
  fuzzers/aflplusplus_optimal/fuzzer.py
  fuzzers/aflplusplus_optimal_shmem/builder.Dockerfile
  fuzzers/aflplusplus_optimal_shmem/fuzzer.py
  fuzzers/aflplusplus_qemu/builder.Dockerfile
  fuzzers/aflplusplus_shmem/builder.Dockerfile
Labels: cla: no

#424 Source based coverage
  .vscode/settings.json
  common/fuzzer_utils.py
  common/test_new_process.py
  docker/generate_makefile.py
  experiment/build/test_builder.py
  fuzzers/coverage_source_based/builder.Dockerfile
  fuzzers/coverage_source_based/fuzzer.py
  fuzzers/test_fuzzers.py
Labels: cla: yes

#438 afl++ performance fix
  fuzzers/aflplusplus/builder.Dockerfile
  fuzzers/aflplusplus_optimal/builder.Dockerfile
  fuzzers/aflplusplus_optimal_shmem/builder.Dockerfile
  fuzzers/aflplusplus_qemu/builder.Dockerfile
  fuzzers/aflplusplus_shmem/builder.Dockerfile
Labels: cla: yes

#441 set related environ var for local running
  experiment/run_experiment.py
Labels: cla: yes

#440 local filestore rsync intermediate folders creation
  common/local_filestore.py
  common/test_local_filestore.py
Labels: cla: yes

#436 Use fuzzer variants for run-time flags only.
  common/fuzzer_utils.py
  docker/gcb/fuzzer.yaml
  docker/gcb/oss-fuzz-fuzzer.yaml
  docker/generate_makefile.py
  experiment/build/gcb_build.py
  experiment/run_experiment.py
  experiment/scheduler.py
  experiment/test_run_experiment.py
  experiment/test_scheduler.py
  service/automatic_run_experiment.py
  service/test_automatic_run_experiment.py
Labels: cla: yes

#443 Add PHP benchmark to service
  service/automatic_run_experiment.py
  service/test_automatic_run_experiment.py
Labels: cla: yes

#422 filestore: enable local_filestore; add unit test
  common/filestore_utils.py
  common/test_filestore_utils.py
  common/test_local_filestore.py
  conftest.py
Labels: cla: yes

#439 Klee sqlite3 merge fixes
  fuzzers/klee/fuzzer.py
Labels: cla: yes

#446 [NFC] typo fix
  analysis/data_utils.py
Labels: cla: yes

#442 Fix/improve queue-based measuring
  common/queue_utils.py
  docker/measure-worker/startup-worker.sh
  experiment/dispatcher.py
  experiment/measurer/measure_manager.py
  experiment/measurer/measure_worker.py
  experiment/measurer/test_measure_manager.py
  experiment/schedule_measure_workers.py
  experiment/scheduler.py
  experiment/test_scheduler.py
Labels: cla: yes

#451 [NFC] rename `experiment_path.gcs` to `experiment_path.filestore`
  common/experiment_path.py
  experiment/build/build_utils.py
  experiment/build/gcb_build.py
  experiment/build/local_build.py
  experiment/measurer.py
Labels: cla: yes

#454 Request new AFL++ experiment
  service/experiment-requests.yaml
Labels: cla: yes

#444 local experiment support
  experiment/conftest.py
  experiment/measurer.py
  experiment/resources/runner-startup-script-template.sh
  experiment/run_experiment.py
  experiment/scheduler.py
  experiment/stop_experiment.py
  experiment/test_data/local-experiment-config.yaml
  experiment/test_scheduler.py
Labels: cla: yes

#456 MOpt fix
  fuzzers/aflplusplus/builder.Dockerfile
  fuzzers/aflplusplus_optimal/builder.Dockerfile
  fuzzers/aflplusplus_optimal/fuzzer.py
  fuzzers/aflplusplus_optimal_shmem/builder.Dockerfile
  fuzzers/aflplusplus_qemu/builder.Dockerfile
  fuzzers/aflplusplus_shmem/builder.Dockerfile
Labels: cla: yes

#460 Request another AFL++ experiment
  service/experiment-requests.yaml
Labels: cla: yes

#464 [NFC] `handle_preemptible` never True for local running
  experiment/scheduler.py
Labels: cla: yes, local

#467 Entropic: Disable 5min Restarts
  fuzzers/entropic/patch.diff
Labels: cla: yes

#466 Add `expect_zero` back for filestore_utils.cp
  common/filestore_utils.py
  common/gsutil.py
  common/local_filestore.py
  experiment/measurer.py
  experiment/test_measurer.py
Labels: cla: yes

#462 remove shared_volume
  experiment/build/local_build.py
  experiment/run_experiment.py
Labels: cla: yes, local

#475 [NFC] #466 minor comment fix
  common/filestore_utils.py
Labels: cla: yes

#469 remove `distinct` for sql query
  experiment/measurer.py
Labels: cla: yes

#477 [woff2] Fix seeds
  benchmarks/woff2-2016-05-06/build.sh
Labels: cla: yes

#461 remove `cloud_project` requirement for local run; add `docker_registry` as a required option for both settings
  common/benchmark_utils.py
  common/test_benchmark_utils.py
  conftest.py
  docs/running-your-own-experiment/running_an_experiment.md
  experiment/build/local_build.py
  experiment/resources/runner-startup-script-template.sh
  experiment/run_experiment.py
  experiment/scheduler.py
  experiment/test_data/experiment-config.yaml
  experiment/test_data/local-experiment-config.yaml
  experiment/test_run_experiment.py
  experiment/test_scheduler.py
Labels: cla: yes

#485 update service/experiment_config.yaml
  service/experiment-config.yaml
Labels: cla: yes

#487 [docs] Improve docs-serve and fix link
  Makefile
  docs/reference/report.md
Labels: cla: yes

#488 again: afl++ improvements
  .github/workflows/fuzzers.yml
  fuzzers/aflplusplus/builder.Dockerfile
  fuzzers/aflplusplus/fuzzer.py
  fuzzers/aflplusplus_optimal/builder.Dockerfile
  fuzzers/aflplusplus_optimal/fuzzer.py
  fuzzers/aflplusplus_optimal_shmem/builder.Dockerfile
  fuzzers/aflplusplus_optimal_shmem/fuzzer.py
  fuzzers/aflplusplus_qemu/builder.Dockerfile
  fuzzers/aflplusplus_qemu/fuzzer.py
  fuzzers/aflplusplus_qemu/runner.Dockerfile
  fuzzers/aflplusplus_shmem/builder.Dockerfile
Labels: cla: yes

#490 Request experiment for AFL++ and entropic
  presubmit.py
  service/experiment-requests.yaml
Labels: cla: yes
